DROP SEQUENCE SEQ_KUNDENNUMMER;
DROP TRIGGER trigger_kundennummer;
DROP TRIGGER CHECK_DUPLICATES;
DROP PROCEDURE DELETE_QUANTITY_0;

DROP TABLE bestellte_artikel CASCADE CONSTRAINTS;
DROP TABLE benutzer CASCADE CONSTRAINTS;
DROP TABLE kunde CASCADE CONSTRAINTS;
DROP TABLE bestellung CASCADE CONSTRAINTS;
DROP TABLE mitarbeiter;
DROP TABLE artikel;
DROP TABLE ARTIKEL_BILD;
DROP TABLE bereitstellung;
DROP TABLE rücksendung CASCADE CONSTRAINTS;
DROP TABLE rücksendegenehmigung CASCADE CONSTRAINTS;
DROP TABLE VERKÄUFER CASCADE CONSTRAINTS;
DROP TABLE lager;
DROP TABLE person;
DROP TABLE plz;
DROP TABLE warenkorb;
DROP TABLE rabatt;

DROP VIEW SHOPPINGCART;
DROP VIEW QUANTITYOFPRODUCTCATEGORIES;

DELETE FROM benutzer;
DELETE FROM kunde;
DELETE FROM person;
DELETE FROM mitarbeiter;
DELETE FROM plz;
DELETE FROM ARTIKEL;
DELETE FROM BESTELLTE_ARTIKEL;
DELETE FROM ARTIKEL_BILD;
DELETE FROM BESTELLUNG;
DELETE FROM WARENKORB;